# Generated by Django 3.2.11 on 2022-01-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180403_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign',
        ),
    ]
